### ISSUE TITLE
websockets

### ISSUE THREAD

**Issue by nikhan** [nytlabs/st-core#149]
we really need a block that affords a way to subscribe to a websocket stream.

**Comment by mikedewar** [comment]
designed as follows (with implications for other streaming sources):

* `wsClient` source
  *  `wsConnect` block
  *  `receive` block
  * `send` block

wsClient source lives in three states: connecting, connected, disconnected. The source's state can only be modified by the `connect` block. The connect block first disconnects, then sets the state to connecting, dials the websocket, fires up the readloop, and sets the state to connected. The Websocket's Stop method can also disconnect. Any error in connect and the block emits the error, sets the socket to disconnected. 

I'm not clear on if we should have a disconnect block.

Websocket source maintains a readloop. The readloop owns a pubsub mechanism. `receive` blocks place a channel in the pubsub mechanism. The channels have a configureable depth. The readloop publishes to the pubsub with an immediate discard default case. 

The `send` block writes directly to the websocket's conn. Send does not block the readloop (unless that turns out to be important).

**Comment by nikhan** [comment]
#214
